/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DevolucionesRouteImport } from './routes/devoluciones'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as MayoristasRouteImport } from './routes/mayoristas'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiCheckoutSessionRouteImport } from './routes/api/checkout-session'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiWompiCheckoutRouteImport } from './routes/api/wompi-checkout'
import { Route as ApiWompiStatusRouteImport } from './routes/api/wompi-status'
import { Route as ApiWompiWebhookRouteImport } from './routes/api/wompi-webhook'
import { Route as CheckoutExitoRouteImport } from './routes/checkout.exito'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucionesRoute = DevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const MayoristasRoute = MayoristasRouteImport.update({
  id: '/mayoristas',
  path: '/mayoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutSessionRoute = ApiCheckoutSessionRouteImport.update({
  id: '/api/checkout-session',
  path: '/api/checkout-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWompiCheckoutRoute = ApiWompiCheckoutRouteImport.update({
  id: '/api/wompi-checkout',
  path: '/api/wompi-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWompiStatusRoute = ApiWompiStatusRouteImport.update({
  id: '/api/wompi-status',
  path: '/api/wompi-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWompiWebhookRoute = ApiWompiWebhookRouteImport.update({
  id: '/api/wompi-webhook',
  path: '/api/wompi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutExitoRoute = CheckoutExitoRouteImport.update({
  id: '/exito',
  path: '/exito',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/historia': typeof HistoriaRoute
  '/mayoristas': typeof MayoristasRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tienda': typeof TiendaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/checkout-session': typeof ApiCheckoutSessionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wompi-checkout': typeof ApiWompiCheckoutRoute
  '/api/wompi-status': typeof ApiWompiStatusRoute
  '/api/wompi-webhook': typeof ApiWompiWebhookRoute
  '/checkout/exito': typeof CheckoutExitoRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/historia': typeof HistoriaRoute
  '/mayoristas': typeof MayoristasRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tienda': typeof TiendaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/checkout-session': typeof ApiCheckoutSessionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wompi-checkout': typeof ApiWompiCheckoutRoute
  '/api/wompi-status': typeof ApiWompiStatusRoute
  '/api/wompi-webhook': typeof ApiWompiWebhookRoute
  '/checkout/exito': typeof CheckoutExitoRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/devoluciones': typeof DevolucionesRoute
  '/envios': typeof EnviosRoute
  '/historia': typeof HistoriaRoute
  '/mayoristas': typeof MayoristasRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/tienda': typeof TiendaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/checkout-session': typeof ApiCheckoutSessionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/wompi-checkout': typeof ApiWompiCheckoutRoute
  '/api/wompi-status': typeof ApiWompiStatusRoute
  '/api/wompi-webhook': typeof ApiWompiWebhookRoute
  '/checkout/exito': typeof CheckoutExitoRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/devoluciones'
    | '/envios'
    | '/historia'
    | '/mayoristas'
    | '/pedido-confirmado'
    | '/privacidad'
    | '/terminos-y-condiciones'
    | '/tienda'
    | '/api/chat'
    | '/api/checkout'
    | '/api/checkout-session'
    | '/api/health'
    | '/api/stripe-webhook'
    | '/api/wompi-checkout'
    | '/api/wompi-status'
    | '/api/wompi-webhook'
    | '/checkout/exito'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/devoluciones'
    | '/envios'
    | '/historia'
    | '/mayoristas'
    | '/pedido-confirmado'
    | '/privacidad'
    | '/terminos-y-condiciones'
    | '/tienda'
    | '/api/chat'
    | '/api/checkout'
    | '/api/checkout-session'
    | '/api/health'
    | '/api/stripe-webhook'
    | '/api/wompi-checkout'
    | '/api/wompi-status'
    | '/api/wompi-webhook'
    | '/checkout/exito'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/carrito'
    | '/checkout'
    | '/contacto'
    | '/devoluciones'
    | '/envios'
    | '/historia'
    | '/mayoristas'
    | '/pedido-confirmado'
    | '/privacidad'
    | '/terminos-y-condiciones'
    | '/tienda'
    | '/api/chat'
    | '/api/checkout'
    | '/api/checkout-session'
    | '/api/health'
    | '/api/stripe-webhook'
    | '/api/wompi-checkout'
    | '/api/wompi-status'
    | '/api/wompi-webhook'
    | '/checkout/exito'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DevolucionesRoute: typeof DevolucionesRoute
  EnviosRoute: typeof EnviosRoute
  HistoriaRoute: typeof HistoriaRoute
  MayoristasRoute: typeof MayoristasRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  TiendaRoute: typeof TiendaRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCheckoutSessionRoute: typeof ApiCheckoutSessionRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWompiCheckoutRoute: typeof ApiWompiCheckoutRoute
  ApiWompiStatusRoute: typeof ApiWompiStatusRoute
  ApiWompiWebhookRoute: typeof ApiWompiWebhookRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devoluciones': {
      id: '/devoluciones'
      path: '/devoluciones'
      fullPath: '/devoluciones'
      preLoaderRoute: typeof DevolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mayoristas': {
      id: '/mayoristas'
      path: '/mayoristas'
      fullPath: '/mayoristas'
      preLoaderRoute: typeof MayoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout-session': {
      id: '/api/checkout-session'
      path: '/api/checkout-session'
      fullPath: '/api/checkout-session'
      preLoaderRoute: typeof ApiCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wompi-checkout': {
      id: '/api/wompi-checkout'
      path: '/api/wompi-checkout'
      fullPath: '/api/wompi-checkout'
      preLoaderRoute: typeof ApiWompiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wompi-status': {
      id: '/api/wompi-status'
      path: '/api/wompi-status'
      fullPath: '/api/wompi-status'
      preLoaderRoute: typeof ApiWompiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wompi-webhook': {
      id: '/api/wompi-webhook'
      path: '/api/wompi-webhook'
      fullPath: '/api/wompi-webhook'
      preLoaderRoute: typeof ApiWompiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/exito': {
      id: '/checkout/exito'
      path: '/exito'
      fullPath: '/checkout/exito'
      preLoaderRoute: typeof CheckoutExitoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutExitoRoute: typeof CheckoutExitoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutExitoRoute: CheckoutExitoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DevolucionesRoute: DevolucionesRoute,
  EnviosRoute: EnviosRoute,
  HistoriaRoute: HistoriaRoute,
  MayoristasRoute: MayoristasRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  TiendaRoute: TiendaRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCheckoutSessionRoute: ApiCheckoutSessionRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWompiCheckoutRoute: ApiWompiCheckoutRoute,
  ApiWompiStatusRoute: ApiWompiStatusRoute,
  ApiWompiWebhookRoute: ApiWompiWebhookRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
